### ISSUE TITLE
JSONDecodeError on cpython library/os.po

### ISSUE THREAD

**Issue by deronnax** [JulienPalard/poautofill#2]
```
$ poautofill library/os.po
Traceback (most recent call last):
  File "/usr/local/bin/poautofill", line 11, in <module>
    sys.exit(fill_pos())
  File "/Users/mdupuy/Library/Python/3.7/lib/python/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mdupuy/Library/Python/3.7/lib/python/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/mdupuy/Library/Python/3.7/lib/python/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mdupuy/Library/Python/3.7/lib/python/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/poautofill/poautofill.py", line 71, in fill_pos
    fill_po(po_file, verbose, target_lang)
  File "/usr/local/lib/python3.7/site-packages/poautofill/poautofill.py", line 55, in fill_po
    entry.msgstr = deepl(entry.msgid, target_lang)
  File "/usr/local/lib/python3.7/site-packages/poautofill/poautofill.py", line 35, in deepl
    "id": 36,
  File "/Users/mdupuy/Library/Python/3.7/lib/python/site-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by JulienPalard** [comment]
Released v0.1.2 fixing this one. Thanks for reporting \o/
